# NCRADS9 - NCRA DS9 Visualization Tool
# Copyright (C) 2026 Yogesh Wadadekar
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""
DS9 backup file writer for NCRADS9.

Author: Yogesh Wadadekar
"""

from datetime import datetime
from pathlib import Path
from typing import Any, Optional, Union


class BackupWriter:
    """Writer for DS9 backup files."""

    VERSION: str = "1.0"

    def __init__(self, filepath: Union[str, Path]) -> None:
        """
        Initialize backup writer.

        Args:
            filepath: Path for the output backup file.
        """
        self.filepath = Path(filepath)
        self._lines: list[str] = []
        self._global_options: dict[str, Any] = {}

    def set_global(self, key: str, value: Any) -> None:
        """
        Set a global option.

        Args:
            key: Option key.
            value: Option value.
        """
        self._global_options[key] = value

    def add_frame(
        self,
        frame_id: str,
        file_path: Optional[str] = None,
        options: Optional[dict[str, Any]] = None,
    ) -> None:
        """
        Add a frame definition.

        Args:
            frame_id: Frame identifier.
            file_path: Path to the image file.
            options: Additional frame options.
        """
        line_parts = [f"frame {frame_id}"]

        if file_path:
            line_parts.append(f"file={file_path}")

        if options:
            for key, value in options.items():
                line_parts.append(f"{key}={value}")

        self._lines.append(" ".join(line_parts))

    def add_region(
        self,
        region_type: str,
        coords: list[Union[int, float, str]],
        properties: Optional[dict[str, Any]] = None,
    ) -> None:
        """
        Add a region definition.

        Args:
            region_type: Type of region (circle, box, etc.).
            coords: Region coordinates.
            properties: Region properties.
        """
        coords_str = ",".join(str(c) for c in coords)
        line = f"{region_type}({coords_str})"

        if properties:
            props_str = " ".join(f"{k}={v}" for k, v in properties.items())
            line = f"{line} # {props_str}"

        self._lines.append(line)

    def add_colormap(self, colormap: str) -> None:
        """
        Add colormap setting.

        Args:
            colormap: Colormap name.
        """
        self._lines.append(f"colormap {colormap}")

    def add_scale(
        self,
        scale_type: str,
        params: Optional[list[Any]] = None,
    ) -> None:
        """
        Add scale setting.

        Args:
            scale_type: Scale type (linear, log, etc.).
            params: Scale parameters.
        """
        line = f"scale {scale_type}"
        if params:
            line += " " + " ".join(str(p) for p in params)
        self._lines.append(line)

    def add_command(self, command: str) -> None:
        """
        Add a raw DS9 command.

        Args:
            command: DS9 command string.
        """
        self._lines.append(command)

    def write(self) -> None:
        """Write the backup file to disk."""
        output_lines = [
            f"# DS9 backup file",
            f"# Generated by NCRADS9 v{self.VERSION}",
            f"# {datetime.now().isoformat()}",
            "",
        ]

        if self._global_options:
            global_parts = ["global"]
            for key, value in self._global_options.items():
                global_parts.append(f"{key}={value}")
            output_lines.append(" ".join(global_parts))
            output_lines.append("")

        output_lines.extend(self._lines)

        with open(self.filepath, "w") as f:
            f.write("\n".join(output_lines))

    def clear(self) -> None:
        """Clear all content."""
        self._lines.clear()
        self._global_options.clear()
